ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed

[versions]
"browser" = 20
"python" = 3
"nodejs" = 1

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "bonjwa-matteo_sad_it_freigestellt"
file = "../bonjwa/Matteo_sad_it_freigestellt_100x72.png"
startx = 0
starty = 0
priority = 1

[[structure]]
name = "bonjwa-logo"
file = "../bonjwa/Bonjwa_Logo_27x27.png"
startx = 100
starty = 44
priority = 5

