ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed

[versions]
"browser" = 20
"python" = 3
"nodejs" = 1

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "flage_nl"
file = "../bonjwa/flagge_nl_0-49.png"
startx = 0
starty = 0
priority = 1

[[structure]]
name = "flage_de"
file = "../bonjwa/flagge_de_50-110.png"
startx = 0
starty = 50
priority = 1


#[[structure]]
#name = "bonjwa-flagge"
#file = "../bonjwa/Flagge_191919.png"
#startx = 360
#starty = 53
#priority = 0


#[[structure]]
#name = "bonjwa-logo"
#file = "../bonjwa/Bonjwa_Logo_27x27.png"
#startx = 80
#starty = 110
#priority = 10

[[structure]]
name = "bonjwa-logo29"
file = "../bonjwa/Bonjwa_Logo_29x29.png"
startx = 81
starty = 111
priority = 10

[[structure]]
name = "bonjwa-matteo-zeigefinger"
file = "../bonjwa/Matteo_zeigefinger.png"
startx = 10
starty = 95
priority = 5

